###**Numpy**

--> stands for Numerical Python and is one of the most useful scientific libraries in Python

--> used for working with arrays

--> lists are good but too slow to process, arrays > list (in huge data)

--> arrays are 50x faster than lists

--> arrays are **collection of elements/values** and **can have one or more dimensions**

--> user guide/Documentation -> [Click me!](https://numpy.org/doc/) -> User Guide PDF

In [ ]:
food_dict = {"name" : ["a","b"],"fav_food" : ["1","2"]}

x = dict(name = "a", fav_food = "1")

print((type(food_dict)) == type(x))

assert type(food_dict) is dict, "not a dictionary"

True


In [ ]:
## First you have to import numpy!
## import <package> as <reference variable>

import numpy as np


#**Arrays**

array() --> used to create a 1D / 2D array

np.array() --> syntax

####**Creating One Dimensional Array 1D Array**


In [ ]:
arr = np.array([10,20,30,40,])
print(arr)

# Output --> [10 20 30 40]
# Looks like a list but it's not a list!
# print(type(arr)) --> Uncomment to check it!

[10 20 30 40]
<class 'numpy.ndarray'>


##**Concept of Arrays**

slicing [x:y]

**arrayExample[x:y]**

indexing [x]

**arrayExample[x]**

 is **applicable in arrays!**

In [ ]:
# Indexing examples
arr = np.array([10,20,30,40,])

print(arr[0])

#negative indexing

print(arr[-1])

#slicing

print(arr[1:3])

10
40
[20 30]


**for loops in array**

In [ ]:
for everyItem in arr:
  print(everyItem)

10
20
30
40


####**Understanding Properties & Methods in Numpy**

shape --> is a property, not a method.

A Property is..

**shape**

A method is..

**method()**

but shape is not a method. No ()

###**Understanding shapes in Arrays**

#### Suppose you're dealing with a 1D Array --> the shape will return..
####1D Array --> return (n,)
####where **n is the number of elements in an array**

#### 2D Array --> return (n,m)
#### where **n is the number of rows**,

#### **m is the number of columns**

In [ ]:
# shape --> used to check the dimensions of an array


In [ ]:
# Example of 1D array / Determining its shape property

print(arr.shape)

# Output 4, 4 --> number of elements in THE array arr([10,20,30,40])

(4,)


###**Understanding dtype**

.dtype --> used to check the dataType of an array

In [ ]:
print(arr.dtype)
# Since arr is integer, therefore it is a int type array(int64)
# If it is a float, the it is float64, if it is a string/bool etc.

int64


In [ ]:
# Example of 2D array

twoD = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD)

print(twoD.shape)
# Output will show 3 rows and 3 columns ( 3by3 dimensions)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


**Creating a 2 by 3 (2x3) Matrix**



In [ ]:
# 2 x 3
# First create 2 lists,
# Then 3 elements

twoD = np.array([[1,2,3] , [4,5,6]])
print(twoD)
print(twoD.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


**Example / Task**

Create a (3x4) matrix and (4x2) matrix

In [ ]:
# 3 x 4 matrix

threefour = np.array([[1,2,3,4] , [5,6,7,8], [9,10,11,12]])
print(threefour)
print(threefour.shape)

# 4 x 2 matrix

fourtwo = np.array([[1,2], [3,4], [5,6], [7,8]])
print(fourtwo)
print(fourtwo.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


#**Understanding Numpy Inbuilt Methods**

1. **zeros()**

-->used to fill an array with 0's

-->at the start of program, you need to fill your arrays with zeros

--> to avoid garbage/wrong values

--> default dataType of zeros() is **float**

In [ ]:
#Create a 1D array that have 0's in the beginning

arr = np.zeros(5)
print(arr)
print(arr.dtype)

#Creating a 2d array with zeros
# np.zeros([dimensions])

arr = np.zeros([3,4])
print(arr)

[0. 0. 0. 0. 0.]
float64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2. **ones()**

--> used to fill an array with 1's

In [ ]:
# ones()
# 1D array

arr = np.ones([7])
print(arr)

#2D array

arr = np.ones([3,4])
print(arr)

[1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3. **full()**

--> used to fill an array with a constant value

In [ ]:
#Creating 1D with .full()
# np.full((NumOfElements), ConstantValue)
arr = np.full((3), 161)
print(arr)



[161 161 161]


4. **random()**

--> used to fill an array with random values

In [ ]:
# .randint(StartNumber,EndNumber,size=(Matrix))

arr = np.random.randint(5,20, size=(4,4))
print(arr)

[[14 11 18 10]
 [19 17 13 19]
 [ 5 13 11  7]
 [10  9 19 11]]


5. **astype()**

--> used to change/convert the dataType of an array

--> int to float, float to int etc.

In [ ]:
# Example

arr = np.ones(6)
print(arr)
print(arr.dtype) # Outputs float

newArr = arr.astype(int)
print(newArr)
print(newArr.dtype) # Outputs integer and int64

#You can write it in this way too!

arr = np.ones(6, dtype=int) #Ordering python to change dtype float to int
print(arr)

[1. 1. 1. 1. 1. 1.]
float64
[1 1 1 1 1 1]
int64


6. **reshape()**

--> used to convert the dimensions of an array

--> 1D array to 2D, 2D to 1D etc

In [ ]:
# Converting 1D into 2D

arr = np.array([10,20,30,40,50,60])
#First determine length/shape of array
print(len(arr))

#2nd, determine how to convert 6 to a 2D array
# Either a 3x2, 2x3, 6x1, 1x6 matrix --> possibilities

#3x2 2x3

twoD = arr.reshape(3,2)
print(twoD)

6
[[10 20]
 [30 40]
 [50 60]]


In [ ]:
# Converting 2D into 1D

twoD = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD.shape) # Just multiply the outputs

oneD = twoD.reshape(9)
print(oneD)



(3, 3)
[1 2 3 4 5 6 7 8 9]


#**Numpy Broadcasting**

--> also important interview question

--> broadcasting - how numpy treats arrays with different shapes during arithmetic operations

--> in numpy you **can perform mathematical operation between arrays**

--> very useful when performing calculations across **uncompatible shapes**

In [ ]:
# Numpy Broadcasting

firstArray = np.array([3,4,5])
secondArray = np.array([2,4,8])

firstArray * secondArray

#Uncompatible Shapes example

arrayOne = np.array([4,5,6])
arrayTwo = np.array([7,8])

# arrayOne * arrayTwo 
# Will result in error, uncomment to check!

**How to avoid broadcasting?**

Rules

1. arrays should be equal (3x3 must be with 3x3, 3x3 cannot be 3x2)
2. one of them is 1

In [ ]:
# one of them is 1 example

firstArray = np.array([3,4,5])
secondArray = np.array([2]) # only 1 element

firstArray * secondArray

array([ 6,  8, 10])